#!/bin/bash

################################################################################
# MODRINTHDL                                                                   #
################################################################################

Update()
{
   read -p "Do you want to delete all current .jar files from mod folder? (Y/n) " yn
   case $yn in 
	  [yY] ) echo "Deleting old .jars";
            cd .. && rm *.jar;
            cd modl;
            echo "Updating...";
            python3 dl.py;
            echo "Moving new .jar files to mod folder";
            mv *.jar ..;
            echo "Done.";
		      exit;;
	  [nN] ) echo "Updating...";
            python3 dl.py;
            echo "Moving new .jar files to mod folder";
            mv *.jar ..;
            echo "Done.";
		      exit;;
	     * ) echo "Invalid response";
		      exit 1;;
   esac
}
Help()
{
   # Display Help
   echo
   echo "Modrinth Mod Downloader"
   echo
   echo "Syntax: modl [-u|h|a|r|s]"
   echo "options:"
   echo "u     Update all mods"
   echo "h     Print this Help"
   echo "a     Add mod to active list"
   echo "r     Remove mod from active list"
   echo "s     Show all active mods"
   echo
   echo  "--------------------------------------------------------"
   echo
   echo "Current active mods"
   echo
   cat details.txt
}

Add()
{
   echo "Current active mods"
   echo "-------------------"
   cat details.txt
   echo
   read -p "Enter Mod ID to add (ex. P7dR8mSH): "
   grep -xqF "$REPLY" projects.txt || echo "$REPLY" >> projects.txt
   echo
   python3 projectcheck.py
}

Remove()
{
   echo "Current active mods"
   echo "-------------------"
   cat details.txt
   echo
   read -p "Enter Mod ID to remove (ex. P7dR8mSH): "
   grep -v "^$REPLY$" projects.txt > tmpfile && mv tmpfile projects.txt
   echo
   python3 projectcheck.py
}

Show()
{
   echo "Current active mods"
   echo "-------------------"
   echo
   cat details.txt
}

while getopts ":uhars" option; do
        case "${option}" in
                u) u=${OPTARG}
                   Update
                   ;;
                h) h=${OPTARG}
                   Help
                   exit;;
                a) a=${OPTARG}
                   Add
                   ;;
                r) r=${OPTARG}
                   Remove
                   ;;
                s) s=${OPTARG}
                   Show
                   ;;
                *) echo "Invalid input, please enter option [-u|h|a|r]"
                   exit;;
        esac
done
